// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/cart.proto

package calculatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteItemFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        int32                  `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemFromCartRequest) Reset() {
	*x = DeleteItemFromCartRequest{}
	mi := &file_proto_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemFromCartRequest) ProtoMessage() {}

func (x *DeleteItemFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemFromCartRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemFromCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteItemFromCartRequest) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *DeleteItemFromCartRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteItemFromCartResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeletedProduct *Product               `protobuf:"bytes,1,opt,name=deletedProduct,proto3" json:"deletedProduct,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteItemFromCartResponse) Reset() {
	*x = DeleteItemFromCartResponse{}
	mi := &file_proto_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemFromCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemFromCartResponse) ProtoMessage() {}

func (x *DeleteItemFromCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemFromCartResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemFromCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteItemFromCartResponse) GetDeletedProduct() *Product {
	if x != nil {
		return x.DeletedProduct
	}
	return nil
}

type GetItemsOfCartByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsOfCartByIdRequest) Reset() {
	*x = GetItemsOfCartByIdRequest{}
	mi := &file_proto_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsOfCartByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsOfCartByIdRequest) ProtoMessage() {}

func (x *GetItemsOfCartByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsOfCartByIdRequest.ProtoReflect.Descriptor instead.
func (*GetItemsOfCartByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemsOfCartByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetItemsOfCartByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       []*Product             `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsOfCartByIdResponse) Reset() {
	*x = GetItemsOfCartByIdResponse{}
	mi := &file_proto_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsOfCartByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsOfCartByIdResponse) ProtoMessage() {}

func (x *GetItemsOfCartByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsOfCartByIdResponse.ProtoReflect.Descriptor instead.
func (*GetItemsOfCartByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemsOfCartByIdResponse) GetProduct() []*Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetCartByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartByUserIdRequest) Reset() {
	*x = GetCartByUserIdRequest{}
	mi := &file_proto_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartByUserIdRequest) ProtoMessage() {}

func (x *GetCartByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetCartByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{4}
}

func (x *GetCartByUserIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCartByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartByUserIdResponse) Reset() {
	*x = GetCartByUserIdResponse{}
	mi := &file_proto_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartByUserIdResponse) ProtoMessage() {}

func (x *GetCartByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetCartByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{5}
}

func (x *GetCartByUserIdResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_proto_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{6}
}

func (x *Cart) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cart) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartRequest) Reset() {
	*x = CreateCartRequest{}
	mi := &file_proto_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartRequest) ProtoMessage() {}

func (x *CreateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartRequest.ProtoReflect.Descriptor instead.
func (*CreateCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCartRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCreated     bool                   `protobuf:"varint,1,opt,name=is_created,json=isCreated,proto3" json:"is_created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartResponse) Reset() {
	*x = CreateCartResponse{}
	mi := &file_proto_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartResponse) ProtoMessage() {}

func (x *CreateCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartResponse.ProtoReflect.Descriptor instead.
func (*CreateCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCartResponse) GetIsCreated() bool {
	if x != nil {
		return x.IsCreated
	}
	return false
}

type AddToCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Cart_Item             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCardRequest) Reset() {
	*x = AddToCardRequest{}
	mi := &file_proto_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCardRequest) ProtoMessage() {}

func (x *AddToCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCardRequest.ProtoReflect.Descriptor instead.
func (*AddToCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{9}
}

func (x *AddToCardRequest) GetItem() *Cart_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddToCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdded       bool                   `protobuf:"varint,1,opt,name=is_added,json=isAdded,proto3" json:"is_added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCardResponse) Reset() {
	*x = AddToCardResponse{}
	mi := &file_proto_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCardResponse) ProtoMessage() {}

func (x *AddToCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCardResponse.ProtoReflect.Descriptor instead.
func (*AddToCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{10}
}

func (x *AddToCardResponse) GetIsAdded() bool {
	if x != nil {
		return x.IsAdded
	}
	return false
}

type Cart_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        int32                  `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Product       *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart_Item) Reset() {
	*x = Cart_Item{}
	mi := &file_proto_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart_Item) ProtoMessage() {}

func (x *Cart_Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart_Item.ProtoReflect.Descriptor instead.
func (*Cart_Item) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{11}
}

func (x *Cart_Item) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *Cart_Item) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{12}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_cart_proto protoreflect.FileDescriptor

const file_proto_cart_proto_rawDesc = "" +
	"\n" +
	"\x10proto/cart.proto\x12\x05proto\"S\n" +
	"\x19DeleteItemFromCartRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\x05R\x06cartId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\"T\n" +
	"\x1aDeleteItemFromCartResponse\x126\n" +
	"\x0edeletedProduct\x18\x01 \x01(\v2\x0e.proto.ProductR\x0edeletedProduct\"+\n" +
	"\x19GetItemsOfCartByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"F\n" +
	"\x1aGetItemsOfCartByIdResponse\x12(\n" +
	"\aproduct\x18\x01 \x03(\v2\x0e.proto.ProductR\aproduct\"(\n" +
	"\x16GetCartByUserIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\":\n" +
	"\x17GetCartByUserIdResponse\x12\x1f\n" +
	"\x04cart\x18\x01 \x01(\v2\v.proto.CartR\x04cart\"/\n" +
	"\x04Cart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\",\n" +
	"\x11CreateCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"3\n" +
	"\x12CreateCartResponse\x12\x1d\n" +
	"\n" +
	"is_created\x18\x01 \x01(\bR\tisCreated\"8\n" +
	"\x10AddToCardRequest\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.proto.Cart_ItemR\x04item\".\n" +
	"\x11AddToCardResponse\x12\x19\n" +
	"\bis_added\x18\x01 \x01(\bR\aisAdded\"N\n" +
	"\tCart_Item\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\x05R\x06cartId\x12(\n" +
	"\aproduct\x18\x02 \x01(\v2\x0e.proto.ProductR\aproduct\"\x19\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xa2\x03\n" +
	"\vCartService\x12C\n" +
	"\n" +
	"CreateCart\x12\x18.proto.CreateCartRequest\x1a\x19.proto.CreateCartResponse\"\x00\x12@\n" +
	"\tAddToCart\x12\x17.proto.AddToCardRequest\x1a\x18.proto.AddToCardResponse\"\x00\x12R\n" +
	"\x0fGetCartByUserId\x12\x1d.proto.GetCartByUserIdRequest\x1a\x1e.proto.GetCartByUserIdResponse\"\x00\x12[\n" +
	"\x12GetItemsOfCartById\x12 .proto.GetItemsOfCartByIdRequest\x1a!.proto.GetItemsOfCartByIdResponse\"\x00\x12[\n" +
	"\x12DeleteItemFromCart\x12 .proto.DeleteItemFromCartRequest\x1a!.proto.DeleteItemFromCartResponse\"\x00B\x16Z\x14./proto;calculatorpbb\x06proto3"

var (
	file_proto_cart_proto_rawDescOnce sync.Once
	file_proto_cart_proto_rawDescData []byte
)

func file_proto_cart_proto_rawDescGZIP() []byte {
	file_proto_cart_proto_rawDescOnce.Do(func() {
		file_proto_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cart_proto_rawDesc), len(file_proto_cart_proto_rawDesc)))
	})
	return file_proto_cart_proto_rawDescData
}

var file_proto_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_cart_proto_goTypes = []any{
	(*DeleteItemFromCartRequest)(nil),  // 0: proto.DeleteItemFromCartRequest
	(*DeleteItemFromCartResponse)(nil), // 1: proto.DeleteItemFromCartResponse
	(*GetItemsOfCartByIdRequest)(nil),  // 2: proto.GetItemsOfCartByIdRequest
	(*GetItemsOfCartByIdResponse)(nil), // 3: proto.GetItemsOfCartByIdResponse
	(*GetCartByUserIdRequest)(nil),     // 4: proto.GetCartByUserIdRequest
	(*GetCartByUserIdResponse)(nil),    // 5: proto.GetCartByUserIdResponse
	(*Cart)(nil),                       // 6: proto.Cart
	(*CreateCartRequest)(nil),          // 7: proto.CreateCartRequest
	(*CreateCartResponse)(nil),         // 8: proto.CreateCartResponse
	(*AddToCardRequest)(nil),           // 9: proto.AddToCardRequest
	(*AddToCardResponse)(nil),          // 10: proto.AddToCardResponse
	(*Cart_Item)(nil),                  // 11: proto.Cart_Item
	(*Product)(nil),                    // 12: proto.Product
}
var file_proto_cart_proto_depIdxs = []int32{
	12, // 0: proto.DeleteItemFromCartResponse.deletedProduct:type_name -> proto.Product
	12, // 1: proto.GetItemsOfCartByIdResponse.product:type_name -> proto.Product
	6,  // 2: proto.GetCartByUserIdResponse.cart:type_name -> proto.Cart
	11, // 3: proto.AddToCardRequest.item:type_name -> proto.Cart_Item
	12, // 4: proto.Cart_Item.product:type_name -> proto.Product
	7,  // 5: proto.CartService.CreateCart:input_type -> proto.CreateCartRequest
	9,  // 6: proto.CartService.AddToCart:input_type -> proto.AddToCardRequest
	4,  // 7: proto.CartService.GetCartByUserId:input_type -> proto.GetCartByUserIdRequest
	2,  // 8: proto.CartService.GetItemsOfCartById:input_type -> proto.GetItemsOfCartByIdRequest
	0,  // 9: proto.CartService.DeleteItemFromCart:input_type -> proto.DeleteItemFromCartRequest
	8,  // 10: proto.CartService.CreateCart:output_type -> proto.CreateCartResponse
	10, // 11: proto.CartService.AddToCart:output_type -> proto.AddToCardResponse
	5,  // 12: proto.CartService.GetCartByUserId:output_type -> proto.GetCartByUserIdResponse
	3,  // 13: proto.CartService.GetItemsOfCartById:output_type -> proto.GetItemsOfCartByIdResponse
	1,  // 14: proto.CartService.DeleteItemFromCart:output_type -> proto.DeleteItemFromCartResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_cart_proto_init() }
func file_proto_cart_proto_init() {
	if File_proto_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cart_proto_rawDesc), len(file_proto_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cart_proto_goTypes,
		DependencyIndexes: file_proto_cart_proto_depIdxs,
		MessageInfos:      file_proto_cart_proto_msgTypes,
	}.Build()
	File_proto_cart_proto = out.File
	file_proto_cart_proto_goTypes = nil
	file_proto_cart_proto_depIdxs = nil
}
